version: '3'

configs:
  logstash.conf:
    file: ./logstash/pipeline/logstash.conf

services:
  elasticsearch:
    image: 
      docker.elastic.co/elasticsearch/elasticsearch-basic:6.2.3
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      CLUSTER_NAME: "elk-cluster"
      NETWORK_HOST: "0.0.0.0"
      DISCOVERY_ZEN_MINIMUM_MASTER_NODES: 1
      DISCOVERY_TYPE: "single-node"
    networks:
      - elk

  logstash:
    image: 
      docker.elastic.co/logstash/logstash:6.2.3
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      HTTP_HOST: "0.0.0.0"
      TCP_PORT: "5000"
      PATH_CONFIG: /usr/share/logstash/pipeline
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    configs:
      - source: logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: 
      docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:

networks:
  elk:
    driver: overlay
